# Generated by Django 4.1.4 on 2022-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_booking', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_ticket', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('cinema_name', models.CharField(max_length=40)),
                ('movie_date', models.DateField()),
                ('show_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(default='', max_length=70)),
                ('language', models.TextField(max_length=160)),
                ('airing_date', models.DateField()),
                ('theater_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.BooleanField(default=False)),
                ('casts', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=160)),
                ('movie_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tickets', models.IntegerField(default=5)),
            ],
        ),
    ]
