# Generated by Django 4.1.4 on 2022-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='categories')),
            ],
        ),
        migrations.AddField(
            model_name='movie_tutorials',
            name='image',
            field=models.FileField(default='exit', upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie_tutorials',
            name='category',
            field=models.ManyToManyField(related_name='book', to='movie_tutorials.category'),
        ),
    ]
