# Generated by Django 4.1.4 on 2022-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tutorials', '0002_category_movie_tutorials_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_tutorials',
            name='category',
        ),
        migrations.AlterField(
            model_name='movie_tutorials',
            name='language',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='movie_tutorials',
            name='theater_name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
