# Generated by Django 4.1.4 on 2022-12-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tutorials', '0003_movie_remove_movie_tutorials_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
